[repository]
name = "hyprScope"

[[plugin]]
name = "hyprScope"
description = "Incremental display magnification for Hyprland"
authors = ["xclusivvv"]
output = "hyprScope.so"
build = [
    "make all"
]
